name: Build Examples

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: [esp32dev, esp32-s2-saola-1, esp32-s3-devkitc-1, esp32-c3-devkitm-1]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install PlatformIO
        run: |
          pip install platformio
      
      - name: Build examples
        run: |
          chmod +x compile_examples.sh
          ./compile_examples.sh
        env:
          PLATFORMIO_BOARD: ${{ matrix.board }}
