[env]
platform = espressif32 @ ~4.4.0
framework = arduino
monitor_speed = 115200

[env:esp32_classic]
board = esp32dev

[env:esp32_s2]
board = esp32-s2-saola-1

[env:esp32_s3]
board = esp32-s3-devkitc-1

[env:esp32_c3]
board = esp32-c3-devkitm-1

[env:esp32_c6]
board = esp32-c6-devkitc-1
platform = espressif32 @ ~6.5.0
